services:
  skinsight_adonis:
    build: .
    container_name: skinsight_backend
    env_file:
      - .env.production.local
    ports:
      - '9090:3333'
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
    networks:
      - skinsight-net

networks:
  skinsight-net:
    external: true
